name: heroicons
description: HeroIcons set of SVG icons in your Flutter app. Both outlined & solid icon version are available.
version: 0.2.1
publish_to: 'none'
homepage: 

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_jolt_ui:
    path: ../jolt_ui

dev_dependencies:
  code_builder: ^4.0.0
  dart_style: ^2.0.1
  recase: ^4.0.0

flutter:
  assets:
    - assets/
    - assets/outline/
    - assets/solid/
